import {MigrationInterface, QueryRunner} from "typeorm";

export class conditions1709255735320 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_91a19e6613534949a4ce6e76ff"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, "customFieldsAveragerating" double precision, "customFieldsNumstars" integer, "customFieldsMake" varchar(255), "customFieldsModel" varchar(255), "customFieldsYear" datetime(6), "customFieldsCountryoforigin" varchar(255), "customFieldsCondition" varchar(255), "customFieldsIsfavorite" boolean, CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite" FROM "product"`, undefined);
        await queryRunner.query(`DROP TABLE "product"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_product" RENAME TO "product"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_91a19e6613534949a4ce6e76ff" ON "product" ("featuredAssetId") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_91a19e6613534949a4ce6e76ff"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, "customFieldsAveragerating" double precision, "customFieldsNumstars" integer, "customFieldsMake" varchar(255), "customFieldsModel" varchar(255), "customFieldsYear" integer, "customFieldsCountryoforigin" varchar(255), "customFieldsCondition" varchar(255), "customFieldsIsfavorite" boolean, CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite" FROM "product"`, undefined);
        await queryRunner.query(`DROP TABLE "product"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_product" RENAME TO "product"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_91a19e6613534949a4ce6e76ff" ON "product" ("featuredAssetId") `, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_91a19e6613534949a4ce6e76ff"`, undefined);
        await queryRunner.query(`ALTER TABLE "product" RENAME TO "temporary_product"`, undefined);
        await queryRunner.query(`CREATE TABLE "product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, "customFieldsAveragerating" double precision, "customFieldsNumstars" integer, "customFieldsMake" varchar(255), "customFieldsModel" varchar(255), "customFieldsYear" datetime(6), "customFieldsCountryoforigin" varchar(255), "customFieldsCondition" varchar(255), "customFieldsIsfavorite" boolean, CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite" FROM "temporary_product"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_product"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_91a19e6613534949a4ce6e76ff" ON "product" ("featuredAssetId") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_91a19e6613534949a4ce6e76ff"`, undefined);
        await queryRunner.query(`ALTER TABLE "product" RENAME TO "temporary_product"`, undefined);
        await queryRunner.query(`CREATE TABLE "product" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "enabled" boolean NOT NULL DEFAULT (1), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "featuredAssetId" integer, "customFieldsAveragerating" double precision, "customFieldsNumstars" integer, "customFieldsMake" varchar(255), "customFieldsModel" varchar(255), "customFieldsYear" datetime(6), "customFieldsCountryoforigin" varchar(255), "customFieldsCondition" varchar(255), "customFieldsIsfavorite" boolean, CONSTRAINT "FK_91a19e6613534949a4ce6e76ff8" FOREIGN KEY ("featuredAssetId") REFERENCES "asset" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "product"("createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite") SELECT "createdAt", "updatedAt", "deletedAt", "enabled", "id", "featuredAssetId", "customFieldsAveragerating", "customFieldsNumstars", "customFieldsMake", "customFieldsModel", "customFieldsYear", "customFieldsCountryoforigin", "customFieldsCondition", "customFieldsIsfavorite" FROM "temporary_product"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_product"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_91a19e6613534949a4ce6e76ff" ON "product" ("featuredAssetId") `, undefined);
   }

}
